# Generated by Django 3.2.9 on 2021-11-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_key_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='type',
        ),
    ]
