# Generated by Django 3.2.9 on 2021-11-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transction_sender_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transction',
            old_name='sender_key',
            new_name='sender',
        ),
    ]
