# Generated by Django 3.2.9 on 2021-11-12 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0005_rename_sender_key_transction_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
