# Generated by Django 3.2.9 on 2021-11-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_key_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transction',
            old_name='receiver_key',
            new_name='receiver',
        ),
    ]
