# Generated by Django 3.2.9 on 2021-11-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_rename_receiver_key_transction_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='type',
            field=models.CharField(choices=[('em', 'email'), ('ph', 'telefone'), ('cp', 'CPF'), ('ra', 'Aleatória')], default='ra', max_length=10, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
