# Generated by Django 3.2.9 on 2021-11-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_key_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='type',
            field=models.CharField(choices=[('email', 'email'), ('phone', 'telefone'), ('cpf', 'CPF'), ('random', 'Aleatória')], max_length=10, verbose_name='Tipo'),
        ),
    ]
